
services:
  postgis_db:
    image: postgis/postgis:18-3.6
    container_name: postgis_container
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgis:/var/lib/postgresql # Persistent data storage
    ports:
      - "5434:5432" # Map container port to host port
    shm_size: "2048m" # Increase shared memory for better performance
    restart: unless-stopped